[package]
name = "morpho"
version = "0.1.0"
authors = ["Evgeny Nerush <eugene.nerush@gmail.com>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
